import type { ListingModelRaw } from "@/lib/realestate/types";

export const mockListingsRaw: ListingModelRaw[] = [
  {
    source: "aqar",
    listing_uri: "https://aqar.example/listings/riyadh-olaya-apt-001",
    goal: "rent",
    rent_frequency: "monthly",
    price: 6800,
    area: 145,
    rooms: 5,
    bedrooms: 3,
    bathrooms: 3,
    living_rooms: 1,
    property_type: "apartment",
    listing_type: "residential",
    city_code: "3",
    region_code: "1",
    district_code: "10100003075",
    latitude: 24.7138,
    longitude: 46.6753
  },
  {
    source: "aqar",
    listing_uri: "https://aqar.example/listings/riyadh-yasmin-villa-002",
    goal: "sale",
    price: 2150000,
    area: 360,
    rooms: 8,
    bedrooms: 5,
    bathrooms: 6,
    living_rooms: 2,
    property_type: "villa",
    listing_type: "residential",
    city_code: "165",
    region_code: "1",
    district_code: "10100165001",
    latitude: 24.8361,
    longitude: 46.6369
  },
  {
    source: "aqar",
    listing_uri: "https://aqar.example/listings/jeddah-hamra-office-003",
    goal: "rent",
    rent_frequency: "annually",
    price: 185000,
    area: 210,
    rooms: 6,
    bathrooms: 2,
    property_type: "office",
    listing_type: "commercial",
    city_code: "18",
    region_code: "2",
    district_code: "10200018112",
    latitude: 21.5291,
    longitude: 39.1725
  },
  {
    source: "aqar",
    listing_uri: "https://aqar.example/listings/dammam-shatea-land-004",
    goal: "sale",
    price: 980000,
    area: 600,
    property_type: "land",
    listing_type: "residential",
    city_code: "13",
    region_code: "5",
    district_code: "10500013012",
    latitude: 26.4344,
    longitude: 50.1033
  },
  {
    source: "aqar",
    listing_uri: "https://aqar.example/listings/khobar-khuzam-shop-005",
    goal: "rent",
    rent_frequency: "quarterly",
    price: 42000,
    area: 90,
    rooms: 2,
    bathrooms: 1,
    property_type: "shop",
    listing_type: "commercial",
    city_code: "113",
    region_code: "5",
    district_code: "10500113022",
    latitude: 26.2734,
    longitude: 50.1996
  },
  {
    source: "aqar",
    listing_uri: "https://aqar.example/listings/madinah-qiblatain-building-006",
    goal: "sale",
    price: 3600000,
    area: 920,
    rooms: 20,
    bedrooms: 12,
    bathrooms: 14,
    living_rooms: 4,
    property_type: "building",
    listing_type: "commercial",
    city_code: "14",
    region_code: "3",
    district_code: "10300014049",
    latitude: 24.5036,
    longitude: 39.5692
  },
  {
    source: "bayut",
    listing_uri: "https://bayut.example/listings/riyadh-malqa-townhouse-101",
    goal: "sale",
    price: 1870000,
    area: 280,
    rooms: 7,
    bedrooms: 4,
    bathrooms: 5,
    living_rooms: 2,
    property_type: "townhouse",
    listing_type: "residential",
    city_code: "3",
    region_code: "1",
    district_code: "10100003145",
    latitude: 24.8219,
    longitude: 46.6023
  },
  {
    source: "bayut",
    listing_uri: "https://bayut.example/listings/riyadh-narjis-floor-102",
    goal: "rent",
    rent_frequency: "monthly",
    price: 5200,
    area: 170,
    rooms: 6,
    bedrooms: 4,
    bathrooms: 3,
    living_rooms: 1,
    property_type: "floor",
    listing_type: "residential",
    city_code: "3",
    region_code: "1",
    district_code: "10100003150",
    latitude: 24.8658,
    longitude: 46.6358
  },
  {
    source: "bayut",
    listing_uri: "https://bayut.example/listings/jeddah-salamah-duplex-103",
    goal: "sale",
    price: 1240000,
    area: 240,
    rooms: 6,
    bedrooms: 4,
    bathrooms: 4,
    living_rooms: 2,
    property_type: "duplex",
    listing_type: "residential",
    city_code: "5",
    region_code: "2",
    district_code: "10200005026",
    latitude: 21.6001,
    longitude: 39.1711
  },
  {
    source: "bayut",
    listing_uri: "https://bayut.example/listings/jeddah-baghdadiyah-warehouse-104",
    goal: "rent",
    rent_frequency: "semi",
    price: 140000,
    area: 1100,
    bathrooms: 2,
    property_type: "warehouse",
    listing_type: "commercial",
    city_code: "18",
    region_code: "2",
    district_code: "10200018032",
    latitude: 21.5038,
    longitude: 39.1918
  },
  {
    source: "bayut",
    listing_uri: "https://bayut.example/listings/makkah-shawqiyah-apartment-105",
    goal: "rent",
    rent_frequency: "annually",
    price: 68000,
    area: 130,
    rooms: 5,
    bedrooms: 3,
    bathrooms: 3,
    living_rooms: 1,
    property_type: "apartment",
    listing_type: "residential",
    city_code: "6",
    region_code: "2",
    district_code: "10200006034",
    latitude: 21.3891,
    longitude: 39.8579
  },
  {
    source: "bayut",
    listing_uri: "https://bayut.example/listings/abha-arin-land-106",
    goal: "sale",
    price: 540000,
    area: 750,
    property_type: "land",
    listing_type: "residential",
    city_code: "15",
    region_code: "6",
    district_code: "10600015026",
    latitude: 18.2164,
    longitude: 42.5053
  },
  {
    source: "dealapp",
    listing_uri: "https://dealapp.example/listings/riyadh-qurtubah-compound-201",
    goal: "rent",
    rent_frequency: "monthly",
    price: 12000,
    area: 220,
    rooms: 7,
    bedrooms: 4,
    bathrooms: 5,
    living_rooms: 2,
    property_type: "compound",
    listing_type: "residential",
    city_code: "3",
    region_code: "1",
    district_code: "10100003101",
    latitude: 24.8151,
    longitude: 46.7707
  },
  {
    source: "dealapp",
    listing_uri: "https://dealapp.example/listings/riyadh-granada-studio-202",
    goal: "rent",
    rent_frequency: "monthly",
    price: 3600,
    area: 54,
    rooms: 1,
    bedrooms: 1,
    bathrooms: 1,
    living_rooms: 1,
    property_type: "studio",
    listing_type: "residential",
    city_code: "3",
    region_code: "1",
    district_code: "10100003155",
    latitude: 24.7824,
    longitude: 46.7409
  },
  {
    source: "dealapp",
    listing_uri: "https://dealapp.example/listings/khobar-rawdah-villa-203",
    goal: "sale",
    price: 1980000,
    area: 400,
    rooms: 9,
    bedrooms: 6,
    bathrooms: 6,
    living_rooms: 2,
    property_type: "villa",
    listing_type: "residential",
    city_code: "13",
    region_code: "5",
    district_code: "10500013026",
    latitude: 26.3051,
    longitude: 50.1848
  },
  {
    source: "dealapp",
    listing_uri: "https://dealapp.example/listings/dammam-faisaliah-office-204",
    goal: "sale",
    price: 1450000,
    area: 320,
    rooms: 9,
    bathrooms: 4,
    property_type: "office",
    listing_type: "commercial",
    city_code: "13",
    region_code: "5",
    district_code: "10500013052",
    latitude: 26.4025,
    longitude: 50.1047
  },
  {
    source: "dealapp",
    listing_uri: "https://dealapp.example/listings/taif-shifa-farm-205",
    goal: "sale",
    price: 880000,
    area: 2200,
    rooms: 4,
    bathrooms: 2,
    property_type: "farm",
    listing_type: "residential",
    city_code: "377",
    region_code: "2",
    district_code: "10200377002",
    latitude: 21.2022,
    longitude: 40.4592
  },
  {
    source: "dealapp",
    listing_uri: "https://dealapp.example/listings/jubail-fanateer-chalet-206",
    goal: "rent",
    rent_frequency: "quarterly",
    price: 78000,
    area: 260,
    rooms: 6,
    bedrooms: 3,
    bathrooms: 3,
    living_rooms: 2,
    property_type: "chalet",
    listing_type: "residential",
    city_code: "13",
    region_code: "5",
    district_code: "10500013004",
    latitude: 27.0174,
    longitude: 49.6584
  }
];
