/* This file is auto-generated by scripts/generate-location-codes.ts */
/* eslint-disable */

export type LocalizedLabel = {
  en: string;
  ar: string;
};

export const regionCodes: Record<string, LocalizedLabel> = {
  "1": {
    "en": "Riyadh",
    "ar": "منطقة الرياض"
  },
  "2": {
    "en": "Makkah",
    "ar": "منطقة مكة المكرمة"
  },
  "3": {
    "en": "Madinah",
    "ar": "منطقة المدينة المنورة"
  },
  "5": {
    "en": "Eastern Province",
    "ar": "المنطقة الشرقية"
  },
  "6": {
    "en": "Asir",
    "ar": "منطقة عسير"
  }
};

export const cityCodes: Record<string, LocalizedLabel> = {
  "3": {
    "en": "Riyadh",
    "ar": "الرياض"
  },
  "5": {
    "en": "At Taif",
    "ar": "الطائف"
  },
  "6": {
    "en": "Makkah",
    "ar": "مكة المكرمة"
  },
  "13": {
    "en": "Dammam",
    "ar": "الدمام"
  },
  "14": {
    "en": "Madinah",
    "ar": "المدينة المنورة"
  },
  "15": {
    "en": "Abha",
    "ar": "ابها"
  },
  "18": {
    "en": "Jeddah",
    "ar": "جدة"
  },
  "113": {
    "en": "Al Jubail",
    "ar": "الجبيل"
  },
  "165": {
    "en": "Hawtat Sudair",
    "ar": "حوطة سدير"
  },
  "377": {
    "en": "Rabigh",
    "ar": "رابغ"
  }
};

export const cityParentCodes: Record<string, { regionCode: string }> = {
  "3": {
    "regionCode": "1"
  },
  "5": {
    "regionCode": "2"
  },
  "6": {
    "regionCode": "2"
  },
  "13": {
    "regionCode": "5"
  },
  "14": {
    "regionCode": "3"
  },
  "15": {
    "regionCode": "6"
  },
  "18": {
    "regionCode": "2"
  },
  "113": {
    "regionCode": "5"
  },
  "165": {
    "regionCode": "1"
  },
  "377": {
    "regionCode": "2"
  }
};

export const districtCodes: Record<string, LocalizedLabel> = {
  "10100003075": {
    "en": "Al Olaya Dist.",
    "ar": "حي العليا"
  },
  "10100003101": {
    "en": "Qurtubah Dist.",
    "ar": "حي قرطبة"
  },
  "10100003145": {
    "en": "Al Malqa Dist.",
    "ar": "حي الملقا"
  },
  "10100003150": {
    "en": "Al Narjis Dist.",
    "ar": "حي النرجس"
  },
  "10100003155": {
    "en": "Ghirnatah Dist.",
    "ar": "حي غرناطة"
  },
  "10100165001": {
    "en": "Al Yasmin Dist.",
    "ar": "حي الياسمين"
  },
  "10200005026": {
    "en": "As Salamah  Dist.",
    "ar": "حي السلامة"
  },
  "10200006034": {
    "en": "Ash Shawqiyah Dist.",
    "ar": "حي الشوقية"
  },
  "10200018032": {
    "en": "Al Baghdadiyah Ash Sharqiyah Dist.",
    "ar": "حي البغدادية الشرقية"
  },
  "10200018112": {
    "en": "Al Hamra Dist.",
    "ar": "حي الحمراء"
  },
  "10200377002": {
    "en": "Ash Shifa Dist.",
    "ar": "حي الشفاء"
  },
  "10300014049": {
    "en": "Al Qiblatayn Dist.",
    "ar": "حي القبلتين"
  },
  "10500013004": {
    "en": "Al Fanar Dist.",
    "ar": "حي الفنار"
  },
  "10500013012": {
    "en": "Ash Shati Al Gharbi Dist.",
    "ar": "حي الشاطئ الغربي"
  },
  "10500013026": {
    "en": "Ar Rawdah Dist.",
    "ar": "حي الروضة"
  },
  "10500013052": {
    "en": "Al Faisaliyah Dist.",
    "ar": "حي الفيصلية"
  },
  "10500113022": {
    "en": "Al Khuzama Dist.",
    "ar": "حي الخزامى"
  },
  "10600015026": {
    "en": "Al Arin Dist.",
    "ar": "حي العرين"
  }
};

export const districtParentCodes: Record<string, { cityCode: string; regionCode: string }> = {
  "10100003075": {
    "cityCode": "3",
    "regionCode": "1"
  },
  "10100003101": {
    "cityCode": "3",
    "regionCode": "1"
  },
  "10100003145": {
    "cityCode": "3",
    "regionCode": "1"
  },
  "10100003150": {
    "cityCode": "3",
    "regionCode": "1"
  },
  "10100003155": {
    "cityCode": "3",
    "regionCode": "1"
  },
  "10100165001": {
    "cityCode": "165",
    "regionCode": "1"
  },
  "10200005026": {
    "cityCode": "5",
    "regionCode": "2"
  },
  "10200006034": {
    "cityCode": "6",
    "regionCode": "2"
  },
  "10200018032": {
    "cityCode": "18",
    "regionCode": "2"
  },
  "10200018112": {
    "cityCode": "18",
    "regionCode": "2"
  },
  "10200377002": {
    "cityCode": "377",
    "regionCode": "2"
  },
  "10300014049": {
    "cityCode": "14",
    "regionCode": "3"
  },
  "10500013004": {
    "cityCode": "13",
    "regionCode": "5"
  },
  "10500013012": {
    "cityCode": "13",
    "regionCode": "5"
  },
  "10500013026": {
    "cityCode": "13",
    "regionCode": "5"
  },
  "10500013052": {
    "cityCode": "13",
    "regionCode": "5"
  },
  "10500113022": {
    "cityCode": "113",
    "regionCode": "5"
  },
  "10600015026": {
    "cityCode": "15",
    "regionCode": "6"
  }
};
